apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-db-agent
  namespace: appdynamics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-agent
  template:
    metadata:
      labels:
        app: db-agent
    spec:
      containers:
      - name: db-agent
        image: appdynamics/db-agent:latest
        resources: 
          requests: 
            cpu: "250m" 
            memory: "512Mi" 
          limits: 
            cpu: "500m" 
            memory: "1Gi"
        env:
        - name: DB_HOST
          value: "postgres.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "tasklistdb"
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: "lombard202601220244269.saas.appdynamics.com"
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value: "lombard202601220244269"
        - name: APPDYNAMICS_AGENT_ACCESS_KEY
          value: "d5apz8dbyuxs"
